from .utility import TextFile
from typing import Optional, Dict
from dataclasses import dataclass, field

@dataclass
class OsuCfg(TextFile):
	data: Dict[str, str] = field(default_factory=dict)
	
	def load(self, filename: Optional[str] = None) -> None:
		super().load(filename)
		
		while not self.eof:
			line = self.readLine('#')
			if not line:
				continue
			kv = line.split(' = ', 1)
			if len(kv) != 2:
				continue
			k, v = kv
			data[k] = v
	
	def save(self, filename: Optional[str] = None) -> None:
		super().save(filename)
		
		print('# osu! configuration', file=self)
		print('# autogenerated by osu.py', file=self)
		print('', file=self)
		print('# IMPORTANT: DO NOT SHARE THIS FILE PUBLICLY.', file=self)
		print('# IT CONTAINS YOUR LOGIN CREDENTIALS IF YOU HAVE THEM SAVED.', file=self)
		print('', file=self)
		for k, v in self.data.items():
			print(f'{k} = {v}', file=self)